databases:
  - name: dpg-cefgeesgqg4b3hb32sc0-a
    databaseName: messi10iniesta8
    user: tadashi
    region: singapore

services:
  - type: web
    name: matchlist
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dpg-cefgeesgqg4b3hb32sc0-a
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false